In [192]:
import pandas as pd

In [193]:
#Imoprting the csv file 
df= pd.read_csv('ebay_mens_perfume.csv')
df.head()

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"

In [194]:
#Renaming the dataset
df= df.rename(columns={'brand':'Perfume_Brand','title':'flavors'})
df.head()

,Perfume_Brand,flavors,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"

In [195]:
#To check whether database contain any NULL values 
df. isnull().any()

Perfume_Brand         True
flavors              False
type                  True
price                False
priceWithCurrency    False
available             True
availableText         True
sold                  True
lastUpdated           True
itemLocation         False
dtype: bool

In [196]:
#To check how many values are Null in Perfume Brand column
df[df['Perfume_Brand'].isna()==1]

,Perfume_Brand,flavors,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
567,NaN,Versace Pour Homme Oud Noir 3.4 oz EDP Cologne...,Eau de Parfum,55.16,US $55.16/ea,NaN,"Limited quantity available / 3,110 sold",3110.0,"May 24, 2024 07:53:50 PDT","Hackensack, New Jersey, United States"

In [197]:
#To replace null values with Versace
df['Perfume_Brand']=df['Perfume_Brand'].fillna('Versace')

In [198]:
#To check how many values are Null in type column
df[df['type'].isna()==1]

,Perfume_Brand,flavors,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
81,Calvin Klein,Ck One by Calvin Klein Cologne Perfume Unisex ...,NaN,23.89,US $23.89/ea,NaN,"Limited quantity available / 54,052 sold",54052.0,"May 24, 2024 03:59:39 PDT","Hackensack, New Jersey, United States"
138,AS SHOW,Bleu De Eau de parfum EDP 100ml 3.4 oz Cologne...,NaN,89.99,US $89.99,5.0,5 available / 5 sold,5.0,"May 14, 2024 20:43:05 PDT","New York,United States, Hong Kong"
606,Milestone Perfumes,Intimation By Milestone Eau de Parfum 3.4 oz Men,NaN,19.89,US $19.89,10.0,More than 10 available / 21 sold,21.0,"May 24, 2024 10:13:17 PDT","Miami, Florida, United States"

In [199]:
#To replace null values with Eau de parfum
df['type']=df['type'].fillna('Eau de parfum')

In [200]:
#To check how many values are Null in available column
[df['available'].isna()==1]

[0      False
 1      False
 2      False
 3      False
 4       True
        ...
 995    False
 996    False
 997    False
 998    False
 999    False
 Name: available, Length: 1000, dtype: bool]

In [201]:
#To drop the available column from dataset
df = df.drop('available', axis=1)

In [202]:
#To look into the top 5 rows
df.head()

,Perfume_Brand,flavors,type,price,priceWithCurrency,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"

In [203]:
#To check how many values are Null in availableText column
df[df['availableText'].isna()==1]

,Perfume_Brand,flavors,type,price,priceWithCurrency,availableText,sold,lastUpdated,itemLocation
405,Jean Paul Gaultier,Jean Paul Gaultier Le Beau Le Parfum Eau De Pa...,Eau de Parfum,169.00,US $169.00,NaN,NaN,NaN,"Winter Haven, Florida, United States"
686,CHANEL,CHANEL Allure Homme Sport 3.4 Oz Men Eau De To...,Eau de Toilette,89.97,US $89.97,NaN,NaN,NaN,"Lakewood, California, United States"
899,Bvlgari,Bvlgari Le Gemme Tygar 3.4oz Men's Eau de Parfum,Eau de Parfum,250.00,US $250.00,NaN,NaN,NaN,"Paterson, New Jersey, United States"

In [204]:
# drop method is used to delete the rows and columns, in this case drop method is used to delect the three rows
df = df.drop([405, 686, 899])

In [205]:
#To check how many values are Null in sold column
df[df['sold'].isna()==1]

,Perfume_Brand,flavors,type,price,priceWithCurrency,availableText,sold,lastUpdated,itemLocation
152,Dossier,Dossier Aromatic Pineapple Eau de Parfum. Size...,Eau de Parfum,20.00,US $20.00/ea,More than 10 available,NaN,NaN,"Los Angeles, California, United States"
792,Bath & Body Works,Bath & Body Works Men's Collection FRESHWATER ...,Cologne,29.97,US $29.97,4 available,NaN,NaN,"Dover, Delaware, United States"
797,Tom Ford,"5 Original M&H Tom Ford Impressions, Tobacco V...",Fragrance Oil,29.99,US $29.99/ea,10 available,NaN,NaN,"St. George, Utah, United States"

In [206]:
# replace the null values with 0
df['sold']=df['sold'].fillna('0')

In [207]:
#To check how many values are Null in lastUpdated column
df[df['lastUpdated'].isna()==1]

,Perfume_Brand,flavors,type,price,priceWithCurrency,availableText,sold,lastUpdated,itemLocation
27,Azzaro,Azzaro The Most Wanted 3.38 oz./100 ml. PARFUM...,Eau de Parfum,87.99,US $87.99,2 available / 4 sold,4.0,NaN,"NEW YORK, United States"
72,Ralph Lauren,New & Sealed! Polo Black by Ralph Lauren 2.5 o...,Eau de Toilette,22.50,US $22.50,More than 10 available / 2 sold,2.0,NaN,"Mesa, Arizona, United States"
127,Dossier,Dossier Citrus Ginger Eau de Parfum. Size: 50m...,Eau de Parfum,20.00,US $20.00/ea,8 available / 23 sold,23.0,NaN,"Los Angeles, California, United States"
147,Unbranded,12 Piece Mixed Men’s Cologne Lot: Assorted sce...,Perfume,48.00,US $48.00,More than 10 available / 7 sold,7.0,NaN,"Webster, Florida, United States"
152,Dossier,Dossier Aromatic Pineapple Eau de Parfum. Size...,Eau de Parfum,20.00,US $20.00/ea,More than 10 available,0,NaN,"Los Angeles, California, United States"
177,Bath & Body Works,OCEAN Cologne Bath & Body Works 3.4 Oz 100 ml ...,Eau de Cologne,28.95,US $28.95,Last One / 5 sold,5.0,NaN,"Chesapeake, Virginia, United States"
213,Bath & Body Works,MAHOGANY TEAKWOOD Cologne 3.4oz Spray Collecti...,Eau de Cologne,35.68,US $35.68/ea,9 available / 12 sold,12.0,NaN,"Chesapeake, Virginia, United States"
280,Dolce & Gabbana,D&G DOLCE & GABBANA THE ONE FOR MEN EDT INTENS...,"Eau De Toilette, Eau De Parfum, Eau De Parfum ...",16.00,US $16.00,More than 10 available / 41 sold,41.0,NaN,"Albany, New York, United States"
285,Giorgio Armani,ARMANI CODE GIORGIO ARMANI PARFUM MINI BOTTLE ...,Eau de Parfum,15.99,US $15.99/ea,More than 10 available / 20 sold,20.0,NaN,"Woodbridge, Virginia, United States"
290,Giorgio Armani,Acqua Di Gio Giorgio Armani For Men EDP 0.5 Fl...,Eau de Parfum,19.95,US $19.95,More than 10 available / 6 sold,6.0,NaN,"Stafford, Texas, United States"
343,Armaf,Club de Nuit Urban Man Elixir by Armaf 3.6 oz ...,Eau de Parfum,38.97,US $38.97,More than 10 available / 4 sold,4.0,NaN,"North Brunswick, New Jersey, United States"
387,Ulric de Varens,Varens For Men Cafe Vanille Eau De Toilette fo...,Eau de Toilette,22.00,US $22.00,49 available / 1 sold,1.0,NaN,"Miami, Florida, United States"
393,Armaf,Armaf Club de Nuit Precieux 1 Extrait de Parfu...,Extrait de Parfum,125.00,US $125.00,More than 10 available / 2 sold,2.0,NaN,"Houston, Texas, United States"
417,Lacoste,Lacoste Style in Play RED Men 4.2 oz 125 ml Ea...,Eau de Toilette,47.34,US $47.34/ea,4 available / 14 sold,14.0,NaN,"Westminster, California, United States"
425,Giorgio Armani,Giorgio Armani Acqua Di Gio 3.4 oz Men's Eau D...,Eau de Toilette,28.99,US $28.99,More than 10 available / 10 sold,10.0,NaN,"College Point, New York, United States"
444,AS PHOTOS,New Carolina-Herrera 212 NYC Men Eau De Toilet...,Eau De Toilette,34.68,US $34.68/ea,8 available / 2 sold,2.0,NaN,"Austin, Texas, United States"
487,Hollister,Hollister Jake Cologne Eau De Cologne 1.7 Oz/5...,Eau de Cologne,28.97,US $28.97/ea,9 available / 12 sold,12.0,NaN,"Chesapeake, Virginia, United States"
493,Paco Rabanne,Paco Rabanne Invictus Legend 5.1 FL OZ / 150 M...,Eau de Parfum,140.00,US $140.00,Last One / 2 sold,2.0,NaN,"Franklin Square, New York, United States"
494,HUGO BOSS,Boss Bottled Infinite By Hugo Boss EDP For Men...,Eau de Parfum,52.99,US $52.99,Last One / 7 sold,7.0,NaN,"Miami, Florida, United States"
499,Kenneth Cole,KENNETH COLE BLACK Cologne for Men 3.4 oz EDT ...,Eau de Toilette,24.15,US $24.15/ea,More than 10 available / 14 sold,14.0,NaN,"Miami, Florida, United States"
536,Milestone Perfumes,Intimation By Milestone Eau de Parfum 3.4 oz Men,Eau de Parfum,34.99,US $34.99,8 available / 4 sold,4.0,NaN,"Virginia Beach, Virginia, United States"
537,ISSEY MIYAKE,L'Eau D'Issey by Issey Miyake Pour Homme Eau D...,Eau de Toilette,26.95,US $26.95,4 available / 5 sold,5.0,NaN,"Oneida, Tennessee, United States"
564,Unbranded,Cologne For Men Lot 2 Piece,Eau de Cologne,18.00,US $18.00/ea,5 available / 3 sold,3.0,NaN,"Phenix City, Alabama, United States"
572,adidas,Adidas Dynamic Pulse Cologne Men 3.4 / 3.3 oz ...,Eau de Toilette,11.58,US $11.58,More than 10 available / 17 sold,17.0,NaN,"New York, New York, United States"
573,PRADA,PRADA Luna Rossa Sport 3.3oz Men's Eau de Toil...,Eau de Toilette,79.99,US $79.99,5 available / 1 sold,1.0,NaN,"Memphis, Tennessee, United States"
581,Branded,*Perfume Para Hombre Con Feromonas De Atraer M...,Perfume,17.99,US $17.99/ea,13 available / 1 sold,1.0,NaN,"Multiple Location, United States"
586,Dolce&Gabbana,Dolce & Gabbana Cologne For Men Eau De Toilett...,Eau de Toilette,27.99,US $27.99,More than 10 available / 9 sold,9.0,NaN,"Jersey City, New Jersey, United States"
596,Dolce&Gabbana,DOLCE & GABBANA LIGHT BLUE FOREVER POUR HOMME ...,Eau de Parfum,75.00,US $75.00,7 available / 1 sold,1.0,NaN,"Franklin Square, New York, United States"
632,GIORGIO ARM.ANI,ACQUA DI GIO Eau De Toilette 3.4 oz/ 100 ml GI...,Eau De Toilette,36.68,US $36.68/ea,9 available / 1 sold,1.0,NaN,"Austin, Texas, United States"
652,Hollister,SO CAL Hollister (3.4oz/100ml( Eau De Cologne...,Eau de Cologne,46.75,US $46.75,7 available / 3 sold,3.0,NaN,"Green Bay, Wisconsin, United States"
673,Hollister,SOCAL by HOLLISTER SO CAL 1.7 oz 50ml EAU DE C...,EAU DE COLOGNE SPRAY,26.75,US $26.75/ea,7 available / 5 sold,5.0,NaN,"Chesapeake, Virginia, United States"
675,Viktor & Rolf,Spicebomb Night Vision 3.04 Oz Eau De Parfum S...,Eau de Parfum,74.85,US $74.85,Last One / 2 sold,2.0,NaN,"Monterey Park, California, United States"
695,Unbranded,Love Bombed Pheromone Cologne for- Men Enhance...,Perfume,13.28,US $13.28/ea,9 available / 6 sold,6.0,NaN,"WA, United States"
696,Cologne,Lane Frost Frosted Cologne,Eau de Cologne,35.00,US $35.00/ea,2 available / 8 sold,8.0,NaN,"Gonzales, Louisiana, United States"
715,Yves Saint Laurent,YSL YVES SAINT LAURENT Y PARFUM L ELIXIR SAMPL...,Eau de Parfum,9.89,US $9.89/ea,More than 10 available / 6 sold,6.0,NaN,"Woodbridge, Virginia, United States"
722,Gucci,Gucci Guilty Pour Homme EDT for Men 3.0 oz / 9...,Eau de Toilette,53.99,US $53.99,3 available / 3 sold,3.0,NaN,"Miami, Florida, United States"
752,Parfums de Marly,CARLISLE by Parfums de Marly - 5ML Travel Samp...,Eau de Parfum,19.99,US $19.99/ea,4 available / 6 sold,6.0,NaN,"Brooklyn, New York, United States"
762,Paco Rabanne,Paco Rabanne 1 One Million Lucky Eau De Toilet...,Eau de Toilette,135.00,US $135.00,8 available / 4 sold,4.0,NaN,"Franklin Square, New York, United States"
770,PRADA,Prada Luna Rossa Black EDP Eau De Parfum 8ml S...,Eau de Parfum,22.99,US $22.99,9 available / 1 sold,1.0,NaN,"Cincinnati, Ohio, United States"
792,Bath & Body Works,Bath & Body Works Men's Collection FRESHWATER ...,Cologne,29.97,US $29.97,4 available,0,NaN,"Dover, Delaware, United States"
797,Tom Ford,"5 Original M&H Tom Ford Impressions, Tobacco V...",Fragrance Oil,29.99,US $29.99/ea,10 available,0,NaN,"St. George, Utah, United States"
847,AXE,Axe Deodorant Body Spray Anarchy For Him Men's...,Deodorant Body Spray,42.99,US $42.99,4 available / 26 sold,26.0,NaN,"Whittier, California, United States"
857,emper,Big Ben London Blanc By Emper Eau De Perfume ...,Eau de Parfum,29.95,US $29.95,4 available / 2 sold,2.0,NaN,"Dallas, Texas, United States"
895,Cologne,PACO RABANNE Phantom Parfum 0.17oz/5mL Mens - ...,Eau de Parfum,24.99,US $24.99,Last One / 2 sold,2.0,NaN,"Lynnwood, Washington, United States"
903,Calvin Klein,Escape For Men by Calvin Klein Eau De Toilette...,Eau de Toilette,24.95,US $24.95,6 available / 8 sold,8.0,NaN,"Oneida, Tennessee, United States"
911,aladdin,Santa fe cologne spray for men by Aladdin 1.7 oz,Eau de Cologne,28.99,US $28.99,8 available / 3 sold,3.0,NaN,"Port Orange, Florida, United States"
915,Rasasi,Hawas by Rasasi 3.4oz EDP for Men NEW SEALED Box,Eau de Parfum,49.50,US $49.50/ea,More than 10 available / 2 sold,2.0,NaN,"Miami, Florida, United States"
945,Giorgio Armani,Lot of 12 - Acqua Di Gio Profondo - Men's Luxu...,Eau de Parfum,24.00,US $24.00,3 available / 2 sold,2.0,NaN,"Arlington Heights, Illinois, United States"
948,Parfums de Marly,PDM PARFUMS DE MARLY LAYTON EXCLUSIF 1.5ml .05...,Parfum,12.00,US $12.00,More than 10 available / 19 sold,19.0,NaN,"Albany, New York, United States"
994,Dolce&Gabbana,Dolce & Gabbana Cologne For Men Eau De Toilett...,Eau de Toilette,27.99,US $27.99/ea,7 available / 24 sold,24.0,NaN,"Des Moines, Iowa, United States"

In [208]:
#Repalcing the null values with a updated time
df['lastUpdated']=df["lastUpdated"].fillna('May 24, 2024 07:56:25 PDT')

In [209]:
#To view the bottom 50 rows
df.tail(50)

,Perfume_Brand,flavors,type,price,priceWithCurrency,availableText,sold,lastUpdated,itemLocation
950,Lapidus,LAPIDUS pour Homme by Ted Lapidus Cologne 3.3 ...,Eau de Toilette,20.08,US $20.08/ea,29 available / 518 sold,518.0,"Apr 23, 2024 03:57:22 PDT","Dallas, Texas, United States"
951,Arabian Oud,Arabian Oud - Arabian Knight EDP For Men 3.4 o...,Fragrances,99.63,US $99.63,3 available / 13 sold,13.0,"May 22, 2024 09:26:42 PDT","Brooklyn, New York, United States"
952,Emporio Armani,Emporio Armani Stronger With You ABSOLUTELY 1....,Perfume,74.99,US $74.99/ea,10 available / 82 sold,82.0,"May 23, 2024 05:39:50 PDT","Katy, Texas, United States"
953,Armaf,Hunter by Armaf cologne for men EDP 3.3 / 3.4 ...,Eau de Parfum,23.62,US $23.62/ea,130 available / 415 sold,415.0,"May 22, 2024 09:23:27 PDT","Dallas, Texas, United States"
954,Perry Ellis,360 Red by Perry Ellis 6.7 / 6.8 oz EDT Cologn...,Eau de Toilette,40.13,US $40.13,"9 available / 2,703 sold",2703.0,"May 22, 2024 15:05:34 PDT","Hackensack, New Jersey, United States"
955,Ralph Lauren,Polo Black by Ralph Lauren EDT 2.5 oz - 75 ml ...,Eau de Toilette,28.99,US $28.99,More than 10 available / 180 sold,180.0,"Mar 18, 2024 09:08:20 PDT","Miami, Florida, United States"
956,Zara,ZARA 8.0 SUMMER Eau Dau Toilette 100 ML,Eau de Toilette,15.00,US $15.00,2 available / 3 sold,3.0,"May 09, 2024 21:13:54 PDT","Houston, Texas, United States"
957,David Beckham,David Beckham The Essence Man 75ml Boxed,Eau de Toilette,37.00,C $37.00,More than 10 available / 60 sold,60.0,"May 21, 2024 07:32:36 PDT","Scarborough, Ontario, Canada"
958,Al Haramain,L'aventure Intense by Al Haramain for men EDP ...,Eau de Parfum,31.98,US $31.98,More than 10 available / 12 sold,12.0,"May 23, 2024 11:09:04 PDT","North Brunswick, New Jersey, United States"
959,Rasasi,RASASI Hawas Ice For Men EDP - 100Ml (3.4Oz),Eau de Parfum,78.00,US $78.00,6 available / 27 sold,27.0,"May 20, 2024 13:03:25 PDT","Astoria, New York, United States"
960,Sterling,"Club De Nuit Intense by Armaf, 6.8 oz EDP Spra...",Eau De Parfum,53.42,US $53.42/ea,More than 10 available / 4 sold,4.0,"May 24, 2024 08:49:52 PDT","Edison, New Jersey, United States"
961,Falic Fashion Group,Perry Ellis for Men 5.0 oz/150 ml Eau de Toile...,Eau de Toilette,29.98,US $29.98/ea,7 available / 14 sold,14.0,"May 05, 2024 09:23:49 PDT","Burlington, Ontario, Canada"
962,HUGO BOSS,BOSS THE SCENT by HUGO BOSS Cologne for Men ed...,Eau de Toilette,47.26,US $47.26/ea,88 available / 52 sold,52.0,"May 09, 2024 11:34:50 PDT","Dallas, Texas, United States"
963,Giorgio Armani,Emporio Armani Stronger With You Intensely 3.3...,Eau de Parfum,94.99,US $94.99/ea,10 available / 420 sold,420.0,"May 23, 2024 23:31:35 PDT","Katy, Texas, United States"
964,Prada,"Prada Luna Rossa Carbon by Prada, 3.4 oz EDT S...",Eau De Toilette,76.65,US $76.65/ea,More than 10 available / 30 sold,30.0,"May 23, 2024 08:58:49 PDT","Edison, New Jersey, United States"
965,Diesel,Diesel Fuel For Life for MEN Cologne 2.5 oz ed...,Eau de Toilette,29.74,US $29.74/ea,19 available / 578 sold,578.0,"May 16, 2024 21:09:42 PDT","Dallas, Texas, United States"
966,Jimmy Choo,Jimmy Choo Man Intense 3.3 / 3.4 oz EDT Cologn...,Eau de Toilette,36.99,US $36.99,4 available / 16 sold,16.0,"May 23, 2024 20:57:06 PDT","Melissa, Texas, United States"
967,Michel Germain,Sexual pour homme by Michel Germain cologne ED...,Eau de Toilette,41.19,US $41.19/ea,21 available / 258 sold,258.0,"May 24, 2024 09:22:09 PDT","Dallas, Texas, United States"
968,Gianni Versace,"NEW Versace Eros , Gianni Versace 6.7oz 200ml ...",Eau de Toilette,69.25,US $69.25,3 available / 19 sold,19.0,"May 22, 2024 04:50:01 PDT","Selinsgrove, Pennsylvania, United States"
969,Lalique,Lalique by Lalique cologne for men EDP 4.2 oz ...,Eau de Parfum,31.47,US $31.47/ea,48 available / 397 sold,397.0,"Apr 24, 2024 22:58:09 PDT","Dallas, Texas, United States"
970,The Baron,The Baron For Gentleman Cologne Natural Atomiz...,Eau de Cologne,34.99,US $34.99,3 available / 1 sold,1.0,"Nov 12, 2023 12:18:20 PST","Canton, Michigan, United States"
971,Jean Paul Gaultier,Scandal Cologne by Jean Paul Gaultier 3.4 oz. ...,Eau de Toilette,55.99,US $55.99/ea,10 available / 368 sold,368.0,"May 22, 2024 14:25:46 PDT","Katy, Texas, United States"
972,Liz Claiborne,Candie's Man by Liz Claiborne 3.4 oz EDT Colog...,Eau de Toilette,18.32,US $18.32/ea,More than 10 available / 211 sold,211.0,"May 22, 2024 17:14:56 PDT","Hackensack, New Jersey, United States"
973,Nina Ricci,Signoricci for Men by Nina Ricci EDT Splash1.7...,Eau de Toilette,120.00,US $120.00/ea,3 available / 7 sold,7.0,"May 14, 2024 13:13:29 PDT","Argyle, Texas, United States"
974,Vince Camuto,Vince Camuto Virtu by Vince Camuto 3.4 oz EDT ...,Eau de Toilette,21.21,US $21.21/ea,8 available / 300 sold,300.0,"May 14, 2024 16:12:02 PDT","Hackensack, New Jersey, United States"
975,Givenchy,Givenchy Gentleman Reserve Privee 3.3 oz Eau d...,Eau de Parfum,80.00,US $80.00/ea,10 available / 197 sold,197.0,"May 24, 2024 03:20:57 PDT","Katy, Texas, United States"
976,Cartier,Declaration Haute Fraicheur by Cartier 3.3 oz ...,Eau de Toilette,49.52,US $49.52,More than 10 available / 20 sold,20.0,"May 11, 2024 20:45:30 PDT","Hackensack, New Jersey, United States"
977,Dolce&Gabbana,Light Blue by Dolce & Gabbana D&G 6.7 oz EDT C...,Eau de Toilette,54.99,US $54.99/ea,2 available / 45 sold,45.0,"Oct 20, 2022 18:26:14 PDT","Bellaire, Texas, United States"
978,Dolce&Gabbana,"Dolce & Gabbana ""K (KING) INTENSE"",3.3oz, Men,...",Eau de Parfum,91.00,US $91.00,3 available / 1 sold,1.0,"May 02, 2024 19:37:12 PDT","Manor, Texas, United States"
979,BRUT,Original Fragrance Cologne by Brut for Men - 5...,Eau de Cologne,9.78,US $9.78,50 available / 8 sold,8.0,"May 23, 2024 13:21:23 PDT","Ronkonkoma, New York, United States"
980,Maison Margiela,Replica Sailing Day by Maison Margiela 3.4 oz ...,Eau de Toilette,84.98,US $84.98,8 available / 42 sold,42.0,"May 21, 2024 07:56:03 PDT","Hackensack, New Jersey, United States"
981,Mercedes Benz,"Mercedes Benz Intense by Mercedes Benz, 4 oz E...",Eau De Toilette,41.87,US $41.87/ea,8 available / 21 sold,21.0,"May 23, 2024 08:57:02 PDT","Edison, New Jersey, United States"
982,Unbranded,VERSE ADONIS Pour Homme cologne for men 3.4oz,Eau de Parfum,13.99,US $13.99,More than 10 available / 9 sold,9.0,"Apr 28, 2024 20:19:23 PDT","Dearborn, Michigan, United States"
983,Carolina Herrera,Bad Boy Le Parfum by Carolina Herrera 3.4 oz. ...,Eau de Parfum,59.99,US $59.99/ea,10 available / 496 sold,496.0,"May 19, 2024 16:41:48 PDT","Katy, Texas, United States"
984,Hollister,Hollister Festival Vibes 3.4 oz EDT Cologne fo...,Eau de Toilette,18.76,US $18.76/ea,5 available / 227 sold,227.0,"May 20, 2024 20:39:02 PDT","Hackensack, New Jersey, United States"
985,Juicy Couture,Dirty English by Juicy Couture EDT Cologne for...,Eau de Toilette,22.60,US $22.60/ea,9 available / 541 sold,541.0,"May 24, 2024 07:10:03 PDT","Hackensack, New Jersey, United States"
986,Polo Ralph Lauren,Polo Blue by Ralph Lauren EDT Spray 4.2 oz for...,Eau de Toilette,33.00,US $33.00/ea,4 available / 401 sold,401.0,"May 23, 2024 05:29:20 PDT","Chico, California, United States"
987,Cuba,Cuba Brazil By Cuba cologne for men EDT 3.3 / ...,Eau de Toilette,10.58,US $10.58/ea,31 available / 391 sold,391.0,"May 23, 2024 18:45:09 PDT","Dallas, Texas, United States"
988,Michael Jordan,Michael Jordan by Michael Jordan 3.4 oz Cologn...,Eau de Cologne,20.48,US $20.48/ea,"Limited quantity available / 2,624 sold",2624.0,"May 22, 2024 21:41:09 PDT","Hackensack, New Jersey, United States"
989,Yves de Sistelle,Thallium Anonymous by Yves de Sistelle Cologne...,Eau de Toilette,18.84,US $18.84/ea,47 available / 674 sold,674.0,"May 21, 2024 07:27:08 PDT","Dallas, Texas, United States"
990,Perry Ellis,"Perry Ellis 360 Red by Perry Ellis, 6.8 oz EDT...",Eau De Toilette,40.72,US $40.72/ea,More than 10 available / 232 sold,232.0,"May 24, 2024 07:58:54 PDT","Edison, New Jersey, United States"
991,Givenchy,Gentleman Boisee by Givenchy cologne for men E...,Eau de Parfum,73.52,US $73.52/ea,4 available / 8 sold,8.0,"May 08, 2024 06:01:12 PDT","Dallas, Texas, United States"
992,Mandarin Duck,Mandarina Duck Black 3.4oz EDT Spray For Men N...,Eau de Toilette,27.99,US $27.99/ea,More than 10 available / 75 sold,75.0,"Nov 02, 2022 03:03:01 PDT","Edison, New Jersey, United States"
993,Franck Olivier,Blue Touch By Franck Olivier Men Cologne 3.3oz...,Eau de Toilette,24.25,US $24.25,More than 10 available / 177 sold,177.0,"May 22, 2024 12:42:51 PDT","North Brunswick, New Jersey, United States"
994,Dolce&Gabbana,Dolce & Gabbana Cologne For Men Eau De Toilett...,Eau de Toilette,27.99,US $27.99/ea,7 available / 24 sold,24.0,"May 24, 2024 07:56:25 PDT","Des Moines, Iowa, United States"
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,US $20.28/ea,"45 available / 1,613 sold",1613.0,"May 24, 2024 08:14:07 PDT","Dallas, Texas, United States"
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,US $30.58,More than 10 available / 31 sold,31.0,"May 23, 2024 08:39:30 PDT",United States
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,US $39.99/ea,2 available / 305 sold,305.0,"May 23, 2024 15:27:18 PDT","Jamaica, New York, United States"
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,US $9.99/ea,2 available / 22 sold,22.0,"May 20, 2024 13:20:54 PDT","Lincoln Park, Michigan, United States"
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,US $17.49/ea,More than 10 available / 24 sold,24.0,"Feb 28, 2024 07:27:01 PST","Keyport, New Jersey, United States"

In [210]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 997, dtype: bool

In [211]:
df['availableText'].str.split(pat='/')
#df['available']=df['availableText'].str.split(pat='/').str[0]
#df['solditems']=df['availableText'].str.split(pat='/').str[1]

0          [More than 10 available ,  116 sold]
1                      [8 available ,  48 sold]
2           [More than 10 available ,  27 sold]
3                     [2 available ,  159 sold]
4      [Limited quantity available ,  156 sold]
                         ...
995                [45 available ,  1,613 sold]
996         [More than 10 available ,  31 sold]
997                   [2 available ,  305 sold]
998                    [2 available ,  22 sold]
999         [More than 10 available ,  24 sold]
Name: availableText, Length: 997, dtype: object

In [212]:
df['available']=df['availableText'].str.split(pat='/').str[0]

In [213]:
df['solditems']=df['availableText'].str.split(pat='/').str[1]

In [214]:
df.head()

,Perfume_Brand,flavors,type,price,priceWithCurrency,availableText,sold,lastUpdated,itemLocation,available,solditems
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",More than 10 available,116 sold
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",8 available,48 sold
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",More than 10 available,27 sold
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",2 available,159 sold
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",Limited quantity available,156 sold

In [215]:
df=df.drop(['availableText'],axis=1)

In [142]:
df.head()

,Perfume_Brand,flavors,type,price,priceWithCurrency,sold,lastUpdated,itemLocation,available,solditems
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",More than 10 available,116 sold
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",8 available,48 sold
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",More than 10 available,27 sold
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",2 available,159 sold
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",Limited quantity available,156 sold

In [216]:
df. isnull().any()

Perfume_Brand        False
flavors              False
type                 False
price                False
priceWithCurrency    False
sold                 False
lastUpdated          False
itemLocation         False
available            False
solditems             True
dtype: bool

In [217]:
df=df.drop(['solditems'],axis=1)

In [145]:
df.head()

,Perfume_Brand,flavors,type,price,priceWithCurrency,sold,lastUpdated,itemLocation,available
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",More than 10 available
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",8 available
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",More than 10 available
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",2 available
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",Limited quantity available

In [218]:
df. isnull().any()

Perfume_Brand        False
flavors              False
type                 False
price                False
priceWithCurrency    False
sold                 False
lastUpdated          False
itemLocation         False
available            False
dtype: bool

In [219]:
df.dtypes

Perfume_Brand         object
flavors               object
type                  object
price                float64
priceWithCurrency     object
sold                  object
lastUpdated           object
itemLocation          object
available             object
dtype: object

In [220]:
df['sold'].astype('int')

0       116
1        48
2        27
3       159
4       156
       ...
995    1613
996      31
997     305
998      22
999      24
Name: sold, Length: 997, dtype: int32

In [221]:
df['sold']=df['sold'].astype('int')

In [222]:
df.dtypes

Perfume_Brand         object
flavors               object
type                  object
price                float64
priceWithCurrency     object
sold                   int32
lastUpdated           object
itemLocation          object
available             object
dtype: object

In [223]:
df['sold'].mean()

763.9608826479438

In [224]:
df['price'].mean()

46.11056168505516

In [225]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [159]:
df.to_csv(r"C:\Users\indum\OneDrive - Pittsburg State University\Data_Analysis\Datasets_cleaned\Cleaned_data")

In [160]:
df.to_csv(r"C:\Users\indum\OneDrive - Pittsburg State University\Data_Analysis\Datasets_cleaned\Cleaned_data.csv")